### ISSUE TITLE
Spacebar too wide

### ISSUE THREAD

**Issue by sppg** [adelnoureddine/harbour-multi-keyboard-layouts#1]
Hello,
  First, thank you very much for this nice piece of work, I really appreciate it.
But since the last sailfishos update, the spacebar is too wide and the buttons for "," and "." and so tiny that it's impossible to click.
Could you have a look please?
Thank you very much

**Comment by adelnoureddine** [comment]
Hi,
thanks for bringing this up. Jolla has improved the default keyboard and widened the space bar by default.
This led to the space bar being too big in my layouts.

Didn't have a chance to fix this yet, but you can tweak it in the qml files, by removing or adjusting the custom width I put for the symbol and enter keys.

For instance tweak and increase the 0.8 in
```implicitWidth: symbolKeyWidthNarrow * 0.8```
Or remove the line to get the default behavior.

**Comment by sppg** [comment]
Hi, thank you very much for your reply.
I tried it in the sobek_frn.qml and sobek_frn_me.qml files but without success :(
I have the impression that the issue is with the value of punctuationKeyWidthNarrow, but not sure.
Do you have any idea please ?

**Comment by sppg** [comment]
I managed to repair it, replacing punctuationKeyWidthNarrow with symbolKeyWidthNarrow * 0.4
in the ContextAwareCommaKey and CharacterKey (".") blocks.
Thank you again for the idea where to look.
For me it's okay now.
If you have time to patch it in a prettier way, it would be great for all the other users.
Thank you again and have a great day

**Comment by adelnoureddine** [comment]
That's perfect, thanks.
I'll try to update and test the layouts on the latest SFOS as soon as I can.
